### ISSUE TITLE
Status of this package?

### ISSUE THREAD

**Issue by dmitshur** [GlenKelley/go-collada#1]
Hi.

If I understand correctly, this is the `go-collada` fork that you were referring to in https://github.com/go3d/go-collada/pull/3#issue-19657348:

> Also, what is the License for this project? Would you mind if I created an open source fork and made changes (like removing global state, so I can run this in parallel within a larger application)?

I wanted to ask what is the status of this package? I've read the README, but I want to quickly confirm. Does it successfully load any .dae files?

It suggests that only Collada 1.5 is supported, does that mean 1.4.1 is not? If I have Collada 1.4.1 files, do you know how I can convert them to 1.5? What modeling tools do you know that can export Collada 1.5 files?

I'm gonna try the latest SketchUp and see. Last time I used it, it was still exporting Collada 1.4.1.

Thank you!

**Comment by dmitshur** [comment]
Just tried go getting this package. The 3 tests pass, so that's promising.

I've noticed the two `.dae` files in this repo seem to state the version of Collada as `1.4.1`. How come that's the case despite 1.4.1 not being mentioned in the README?

**Comment by dmitshur** [comment]
/cc @GlenKelley

You're not [watching](https://github.com/GlenKelley/go-collada/watchers) your own package, does that mean it's abandoned or is that unintentional?

**Comment by GlenKelley** [comment]
Hi Shurcool,

It was unintentional, I'm watching it now. I am not maintaining this package, but I'll add an MIT or otherwise permissive license to the package when I get the time. Please feel free to fork it and use it in any way you see fit.

My apologies for the lack of documentation of this package. It was created for my own purposes when experimenting with loading models to build an OpenGL renderer in Go.

**Comment by dmitshur** [comment]
Hey, thanks for the quick reply.

I tried it out on one of my 1.4.1 .dae files (exported from SketchUp a while ago) and it seems to have loaded it okay. I see lots of data and at first glance it looks like vertices, etc. are there.

> I am not maintaining this package, but I'll add an MIT or otherwise permissive license to the package when I get the time. Please feel free to fork it and use it in any way you see fit.

It's already licensed under MIT, which is great. I'm just exploring this for now, not planning to do a lot of work yet.

>  It was created for my own purposes when experimenting with loading models to build an OpenGL renderer in Go.

Nice! I'm also interested in being able to load/convert Collada files for purposes of rendering them using OpenGL in Go (primarily for [this](https://github.com/shurcooL/Hover) project, but maybe down the line also for porting [this](https://github.com/shurcooL/Slide) one too).

Just curious, are you no longer using Go? Or are you doing other things?

**Comment by GlenKelley** [comment]
In response to your question about the collada version (1.5 vs 1.4.1).

I implemented the spec of the documentation for 1.5, but when I created the models using blender, it generated 1.4.1 dea documents. I just realised only the tests actually check the version, but the implementation itself does not. Consider that an oversight.

I still use go for my own personal projects, but have been busy in the last 12 months so I have not had the time to continue these projects.

**Comment by dmitshur** [comment]
> It was created for my own purposes when experimenting with loading models to build an OpenGL renderer in Go.

Was it your [github.com/GlenKelley/carsim](https://github.com/GlenKelley/carsim) app? I just tried to see if I could get it to compile, and after fixing one minor thing (PR [here](https://github.com/GlenKelley/go-gl/pull/1)), it just worked! Really nice.

![image](https://cloud.githubusercontent.com/assets/1924134/5551539/039e8282-8b88-11e4-8cda-fc0abde4bf8c.png)

That gives me confidence that I can look more into this code and it's actually usable. Thank you for sharing it.

**Comment by dmitshur** [comment]
This package is working and useful. It has been added to awesome-go list in https://github.com/avelino/awesome-go/pull/253. Closing here. Thanks for making it!
